### ISSUE TITLE
Applying a custom date range doesn't seem to stick

### ISSUE THREAD

**Issue by georgiamoon** [bocoup/mlab-vis-client#196] opened 2016-10-20 02:13 UTC
I'm not sure what's happening, but when I try to set the custom date range, I get bumped back to my current view and out of the date picker.

**Comment by pbeshai** [comment] 2016-11-01 14:31
I haven't been able to reproduce this. Maybe this is due to the extraneous "Custom Range" button confusing users since it doesn't do anything if you click it? I removed it now in any case while updating #236.

**Comment by georgiamoon** [comment] 2016-11-01 14:43
Ahhh... yes, I was trying to use the custom range... so I can't do that?

I would like to be able to do a custom range....

**Comment by pbeshai** [comment] 2016-11-01 14:57
No you can do it, you just click in the calendar to change the days. That custom range button just did nothing besides highlight if you manually set the dates. It was confusing since it looks like a button you can click, but it wasn't, so I removed it.

**Comment by georgiamoon** [comment] 2016-11-01 16:56
I see -- so custom date range, by interacting with the datepicker does ** work ** but the "custom range" button doesn't do anything. Got it.

Removing the button makes sense then I think.

**Comment by pbeshai** [comment] 2016-11-01 17:10
Yea it was a weird design by the component we're using. Going to close this issue.

**Closed by pbeshai** 2016-11-01 17:10 UTC
